#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS AND SETTINGS
#=================================================

influxdb_admin_token=$(ynh_string_random --length=64 --filter='A-Za-z0-9-_')

# Check if the retention value is valid
if ! echo "$influxdb_bucket_retention" | grep -qE '^(0|[0-9]+(ns|u|µ|ms|s|m|h|d|w))$'; then
    ynh_die "Invalid retention value. It should be either 0 (infinite) or a number followed by a duration unit (ns, u, µ, ms, s, m, h, d, w)."
fi

ynh_app_setting_set --key=influxdb_org_name --value=$influxdb_org_name
ynh_app_setting_set --key=influxdb_bucket_name --value=$influxdb_bucket_name
ynh_app_setting_set --key=influxdb_bucket_retention --value=$influxdb_bucket_retention
ynh_app_setting_set --key=influxdb_admin_token --value=$influxdb_admin_token

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id=influxdb2
ynh_setup_source --dest_dir="$install_dir" --source_id=influx

#=================================================
# ADD CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.toml.example" --destination="$install_dir/config.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Time-series database" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START AND ENABLE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="enable"
ynh_systemctl --service=$app --action="start"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Configuring $app ..."

ynh_systemctl --service=$app --action="start"  --wait_until="msg=Listening"

# First setup InfluxDB v2 using influx
ynh_exec_as_app $install_dir/influx setup --force --skip-verify --name default --configs-path $install_dir/.influxdbv2/configs --host http://localhost:$port --bucket $influxdb_bucket_name --org $influxdb_org_name --username $admin --password "$password" --retention $influxdb_bucket_retention --token $influxdb_admin_token

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
